name: build

on:
  workflow_dispatch:

jobs:
  secure-rdp:
    runs-on: windows-latest
    timeout-minutes: 3600

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Configure 
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0 -Force
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 0 -Force
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "SecurityLayer" -Value 0 -Force
          netsh advfirewall firewall delete rule name="RDP-Tailscale"
          netsh advfirewall firewall add rule name="RDP-Tailscale" dir=in action=allow protocol=TCP localport=3389
          Restart-Service -Name TermService -Force

      

      - name: start
        env:
          JS_SCRIPT_BASE64: ${{ secrets.JS_SCRIPT_BASE64 }}
          TARGET_LINK: ${{ secrets.TARGET_LINK }}
        run: |
          # Install puppeteer dependencies
          npm install puppeteer puppeteer-core

          # Write TARGET_LINK secret to link.txt
          Set-Content -Path "link.txt" -Value $env:TARGET_LINK -NoNewline

          # Decode JS_SCRIPT_BASE64 secret into v77.js
          $bytes = [System.Convert]::FromBase64String($env:JS_SCRIPT_BASE64)
          $decodedScript = [System.Text.Encoding]::UTF8.GetString($bytes)
          Set-Content -Path "v77.js" -Value $decodedScript

      - name: Run JS 
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          Start-Process node -ArgumentList "v77.js" -NoNewWindow

      - name: show progress
        run: |
           echo ""
